apiVersion: v1
kind: Service
metadata:
  name: qr-flask-app-service
  namespace: app-ns
spec:
  selector:
    app: qr-flask-app
  ports:
  - protocol: TCP
    port: {{ .Values.servicePort }}
    targetPort: {{ .Values.containerPort }}
  type: {{ .Values.service.type }}
