name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        cd app_py
        pip install -r requirements.txt

    - name: Run tests
      run: |
        pytest

  build-and-push-docker:
    runs-on: ubuntu-latest
    needs: test

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Log in to DockerHub
      run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u bola278 --password-stdin

    - name: Build Docker image
      run: cd app_py && docker build -t bola278/qr-code-app:latest .

    - name: Push Docker image
      run: docker push bola278/qr-code-app:latest

    - name: Tag Docker image if tag is present
      if: startsWith(github.ref, 'refs/tags/')
      run: |
        TAG_NAME=${GITHUB_REF##*/}
        docker tag bola278/qr-code-app:latest bola278/qr-code-app:$TAG_NAME
        docker push bola278/qr-code-app:$TAG_NAME
